name: Pipeline
on: 
  push:
    branches:
      - main

jobs:
  build:
    name: build image
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: build
        env:
          DOCKER_PWD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo ${DOCKER_PWD} | docker login -u bilalmahmood19 --password-stdin
          make docker-build-push
          docker logout
